### ISSUE TITLE
missing queue submodule?

### ISSUE THREAD

**Issue by caedesvvv** [progrium/wolverine#1]
i get this when trying to run miyamoto, maybe some files are missing?

~/miyamoto$ miyamoto -p 8123
Traceback (most recent call last):
  File "/usr/bin/miyamoto", line 5, in <module>
    pkg_resources.run_script('miyamoto==0.0.2', 'miyamoto')
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 1166, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.5/site-packages/miyamoto-0.0.2-py2.5.egg/EGG-INFO/scripts/miyamoto", line 11, in <module>
    from miyamoto.web import MiyamotoResource
  File "/usr/lib/python2.5/site-packages/miyamoto-0.0.2-py2.5.egg/miyamoto/web.py", line 6, in <module>
    from miyamoto import pubsub, stream
  File "/usr/lib/python2.5/site-packages/miyamoto-0.0.2-py2.5.egg/miyamoto/pubsub.py", line 9, in <module>
    from miyamoto import queue
ImportError: cannot import name queue

---

**Comment by berb** [comment]
I can second that.

**Comment by drewp** [comment]
It's probably https://github.com/progrium/hookah/raw/master/hookah/queue.py and https://github.com/progrium/hookah/raw/master/hookah/storage.py

**Comment by white-gecko** [comment]
Where do I have to put those files? And @progrium could integrate them into this repo?

**Comment by drewp** [comment]
IIRC you can just put them in the miyamoto directory, next to pubsub.py
