### ISSUE TITLE
Unhandled error in Deferred:

### ISSUE THREAD

**Issue by white-gecko** [progrium/wolverine#3]
I get following error, when I try to publish something to the hub.

```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 167, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 216, in render
    return m(request)
  File "/home/natanael/.local/lib/python2.7/site-packages/miyamoto-0.0.2-py2.7.egg/miyamoto/pubsub.py", line 136, in render_POST
    publish(url)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1187, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
    result = g.send(result)
  File "/home/natanael/.local/lib/python2.7/site-packages/miyamoto-0.0.2-py2.7.egg/miyamoto/pubsub.py", line 43, in publish
    if len(subscribers):
exceptions.TypeError: object of type 'NoneType' has no len()
```

Am I doing something wrong or is it a bug?
The tests are running through without any problems.

**Comment by arski** [comment]
well, if you look at the location of the error, and how "subscribers" is fetched, you'll see that if a topic has no subscriptions, "subscribers" will be "None", causing the error. Obviously this is not implemented nicely, but just adding subscriptions to a topic before publishing anything solves the issue too.

**Comment by white-gecko** [comment]
I still get the same error, even though I have subscribed to the topic before. How can I see which subscriptions are active in the hub? The README says: "The root path is the hub endpoint. There is a preliminary/debug interface if you browse to it.". If I open `http://localhost:8123` in my browser I get "No Such Resource No such child resource."

**Comment by white-gecko** [comment]
Using the fork of @caedesvvv I don't get this error anymore. But get following error:

```
Fetching http://localhost/~natanael/myfeed.xml for 1 subscribers
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 368, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1101, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
    result = g.send(result)
  File "/home/natanael/.local/lib/python2.7/site-packages/miyamoto-0.0.2-py2.7.egg/miyamoto/pubsub.py", line 57, in publish
    ahash = hmac.HMAC(secret, page, hashlib.sha1)
  File "/usr/lib/python2.7/hmac.py", line 68, in __init__
    if len(key) > blocksize:
exceptions.TypeError: object of type 'NoneType' has no len()
```

is it because I didn't specify any secret?
